title: Wei Cai's Academic Homepage
page-top-title: Wei Cai
top-section-bg-text: Data Science & Big Data Technology
home-subtitle: Wei Cai&ensp;|&ensp;Data Science & Big Data Technology
copyright-text: '&copy; Wei Cai 2025-2026. All Rights Reserved.'
